// Generated by LiveScript 1.4.0
(function(){
  var os, fs, net, colors, ribcage, _, h, p, spawn, lwebServer, queryProtocol, env;
  os = require('os');
  fs = require('fs');
  net = require('net');
  colors = require('colors');
  ribcage = require('ribcage');
  _ = require('underscore');
  h = require('helpers');
  p = require('bluebird');
  spawn = require('child_process').spawn;
  lwebServer = require('lweb3/transports/server/nssocket');
  queryProtocol = require('lweb3/protocols/query');
  env = {
    settings: {
      port: 12312
    }
  };
  ribcage.init(env, function(){
    env.log("init", {}, "init");
    env.server = new lwebServer.nssocketServer({
      port: env.settings.port,
      name: 'ids',
      logger: env.logger.child({
        tags: 'ids'
      })
    });
    env.server.on('end', function(){
      env.log('server down', {}, 'error');
      return process.exit(1);
    });
    return env.server.subscribe(true, function(msg){
      return true;
    });
  });
}).call(this);
